<template>
  <div class="flex">
    <div class="flex bg-gray-50 select-none">
      <div>
        <ul class="sticky top-0 font-mono font-bold text-base w-12 sm:w-16">
          <li>
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/"
              exact
            >
              ✹
            </nuxt-link>
          </li>
          <li>
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/prefacio"
              exact
            >
              ⊟
            </nuxt-link>
          </li>
          <li>
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/noticia-bibliografica"
              exact
            >
              ≋
            </nuxt-link>
          </li>
          <li class="border-b-2 border-white">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/dentro-e-fora-do-humano"
              exact
            >
              ⊙
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/01"
              exact
            >
              Ⅰ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/02"
              exact
            >
              Ⅱ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/03"
              exact
            >
              Ⅲ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/04"
              exact
            >
              Ⅳ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/05"
              exact
            >
              Ⅴ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/06"
              exact
            >
              Ⅵ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/07"
              exact
            >
              Ⅶ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/08"
              exact
            >
              Ⅷ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/09"
              exact
            >
              Ⅸ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/10"
              exact
            >
              Ⅹ
            </nuxt-link>
          </li>
          <li class="bg-gray-100">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/11"
              exact
            >
              Ⅺ
            </nuxt-link>
          </li>
          <li class="bg-gray-100 border-b-2 border-white">
            <nuxt-link
              class="
                flex
                text-gray-400
                hover:text-black
                py-3
                sm:py-4
                relative
                w-full
                justify-center
              "
              to="/12"
              exact
            >
              Ⅻ
            </nuxt-link>
          </li>
        </ul>
      </div>
    </div>
    <main class="flex-1 p-4 sm:p-8 lg:p-16">
      <h1>
        <span
          class="
            block
            text-base text-center text-purple-600
            font-bold
            tracking-wide
          "
        >
          A comment on the Devil's Love
        </span>
      </h1>
      <Nuxt />
    </main>
  </div>
</template>
<script>
export default {
  head() {
    return {
      title: "A comment on the Devil's Love",
    }
  },

  mounted() {},
}
</script>
